/* JS */ gapi.loaded_1(function(_){var window=this;
var Be;_.ye=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};_.ze=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Ae=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};Be="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");_.Ce=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Be.length;f++)c=Be[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}}; _.De=function(a){var b=arguments.length;if(1==b&&(0,_.ma)(arguments[0]))return _.De.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};

_.Ej=function(a,b){for(var c=a.split("."),d=b||_.r,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};_.Fj=function(a,b){return 1==_.ic.splice.call(a,b,1).length};_.Gj=function(a,b){var c=(0,_.jc)(a,b),d;(d=0<=c)&&(0,_.Fj)(a,c);return d};_.Hj=function(a,b){var c;t:{c=a.length;for(var d=(0,_.pa)(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break t}c=-1}return 0>c?null:(0,_.pa)(a)?a.charAt(c):a[c]};
_.Ij=function(){};_.Ij.prototype.$e=!1;_.Ij.prototype.cb=function(){return this.$e};_.Ij.prototype.fa=function(){this.$e||(this.$e=!0,this.T())};_.Ij.prototype.T=function(){if(this.Va)for(;this.Va.length;)this.Va.shift()()};_.Jj=function(a){a&&"function"==typeof a.fa&&a.fa()};
_.Kj=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.Mg=!1;this.Ax=!0};_.Kj.prototype.T=function(){};_.Kj.prototype.fa=function(){};_.Kj.prototype.stopPropagation=function(){this.Mg=!0};_.Kj.prototype.preventDefault=function(){this.defaultPrevented=!0;this.Ax=!1};
var Lj=function(a){Lj[" "](a);return a};Lj[" "]=_.Kd;var Mj=!_.O||(0,_.je)(9),Nj=!_.O||(0,_.je)(9),Oj=_.O&&!(0,_.he)("9");!_.Zd||(0,_.he)("528");_.Yd&&(0,_.he)("1.9b")||_.O&&(0,_.he)("8")||_.Xd&&(0,_.he)("9.5")||_.Zd&&(0,_.he)("528");_.Yd&&!(0,_.he)("8")||_.O&&(0,_.he)("9");_.Pj=_.O?"focusin":"DOMFocusIn";_.Qj=_.O?"focusout":"DOMFocusOut";_.Rj=_.Zd?"webkitTransitionEnd":_.Xd?"otransitionend":"transitionend";_.Sj=function(a,b){_.Kj.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.Im=!1;this.A=null;a&&this.$a(a,b)};(0,_.u)(_.Sj,_.Kj);var Tj=[1,4,2];
_.Sj.prototype.$a=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(_.Yd){var e;t:{try{Lj(d.nodeName);e=!0;break t}catch(f){}e=!1}e||(d=null)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=_.Zd||void 0!==a.offsetX?a.offsetX:a.layerX;this.offsetY=_.Zd||void 0!==a.offsetY?a.offsetY:a.layerY;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:
a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Im=_.Pd?a.metaKey:a.ctrlKey;this.state=a.state;this.A=a;a.defaultPrevented&&this.preventDefault()};_.Uj=function(a){return(Mj?0==a.A.button:"click"==a.type?!0:!!(a.A.button&Tj[0]))&&!(_.Zd&&_.Pd&&a.ctrlKey)};
_.Sj.prototype.stopPropagation=function(){_.Sj.J.stopPropagation.call(this);this.A.stopPropagation?this.A.stopPropagation():this.A.cancelBubble=!0};_.Sj.prototype.preventDefault=function(){_.Sj.J.preventDefault.call(this);var a=this.A;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Oj)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};_.Sj.prototype.OC=function(){return this.A};_.Sj.prototype.T=function(){};
var Xj;var Vj;Vj="closure_listenable_"+(1E6*Math.random()|0);_.Wj=function(a){try{return!(!a||!a[Vj])}catch(b){return!1}};Xj=0;var Yj=function(a,b,c,d,e){this.Jg=a;this.C=null;this.src=b;this.type=c;this.B=!!d;this.If=e;this.key=++Xj;this.A=this.Rk=!1},Zj=function(a){a.A=!0;a.Jg=null;a.C=null;a.src=null;a.If=null};var bk;var ck;var ak=function(a){this.src=a;this.A={};this.B=0};ak.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.A[f];a||(a=this.A[f]=[],this.B++);var g=bk(a,b,d,e);-1<g?(b=a[g],c||(b.Rk=!1)):(b=new Yj(b,this.src,f,!!d,e),b.Rk=c,a.push(b));return b};ak.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.A))return!1;var e=this.A[a];b=bk(e,b,c,d);return-1<b?(Zj(e[b]),(0,_.Fj)(e,b),0==e.length&&(delete this.A[a],this.B--),!0):!1};
ck=function(a,b){var c=b.type;if(!(c in a.A))return!1;var d=(0,_.Gj)(a.A[c],b);d&&(Zj(b),0==a.A[c].length&&(delete a.A[c],a.B--));return d};_.dk=function(a,b,c,d,e){a=a.A[b.toString()];b=-1;a&&(b=bk(a,c,d,e));return-1<b?a[b]:null};bk=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.A&&f.Jg==b&&f.B==!!c&&f.If==d)return e}return-1};
var rk;var mk;var pk;var qk;var lk;var kk;var gk;var fk;var ek;ek="closure_lm_"+(1E6*Math.random()|0);fk={};gk=0;_.R=function(a,b,c,d,e){if((0,_.ma)(b)){for(var f=0;f<b.length;f++)(0,_.R)(a,b[f],c,d,e);return null}c=(0,_.hk)(c);return(0,_.Wj)(a)?a.P(b,c,d,e):(0,_.ik)(a,b,c,!1,d,e)};
_.ik=function(a,b,c,d,e,f){if(!b)throw Error("q");var g=!!e,k=(0,_.jk)(a);k||(a[ek]=k=new ak(a));c=k.add(b,c,d,e,f);if(c.C)return c;d=kk();c.C=d;d.src=a;d.Jg=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(lk(b.toString()),d);gk++;return c};kk=function(){var a=mk,b=Nj?function(c){return a.call(b.src,b.Jg,c)}:function(c){c=a.call(b.src,b.Jg,c);if(!c)return c};return b};
_.nk=function(a,b,c,d,e){if((0,_.ma)(b))for(var f=0;f<b.length;f++)(0,_.nk)(a,b[f],c,d,e);else c=(0,_.hk)(c),(0,_.Wj)(a)?a.Ea(b,c,d,e):a&&(a=(0,_.jk)(a))&&(b=(0,_.dk)(a,b,c,!!d,e))&&(0,_.ok)(b)};_.ok=function(a){if((0,_.Ub)(a)||!a||a.A)return!1;var b=a.src;if((0,_.Wj)(b))return ck(b.re,a);var c=a.type,d=a.C;b.removeEventListener?b.removeEventListener(c,d,a.B):b.detachEvent&&b.detachEvent(lk(c),d);gk--;(c=(0,_.jk)(b))?(ck(c,a),0==c.B&&(c.src=null,b[ek]=null)):Zj(a);return!0};
lk=function(a){return a in fk?fk[a]:fk[a]="on"+a};qk=function(a,b,c,d){var e=1;if(a=(0,_.jk)(a))if(b=a.A[b.toString()])for(b=(0,_.Id)(b),a=0;a<b.length;a++){var f=b[a];f&&f.B==c&&!f.A&&(e&=!1!==pk(f,d))}return Boolean(e)};pk=function(a,b){var c=a.Jg,d=a.If||a.src;a.Rk&&(0,_.ok)(a);return c.call(d,b)};
mk=function(a,b){if(a.A)return!0;if(!Nj){var c=b||(0,_.Ej)("window.event"),d=new _.Sj(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){t:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break t}catch(g){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.currentTarget;f;f=f.parentNode)c.push(f);for(var f=a.type,k=c.length-1;!d.Mg&&0<=k;k--)d.currentTarget=c[k],e&=qk(c[k],f,!0,d);for(k=0;!d.Mg&&k<c.length;k++)d.currentTarget=c[k],e&=qk(c[k],f,!1,d)}return e}return pk(a,new _.Sj(b,this))}; _.jk=function(a){a=a[ek];return a instanceof ak?a:null};rk="__closure_events_fn_"+(1E9*Math.random()>>>0);_.hk=function(a){return(0,_.Sb)(a)?a:a[rk]||(a[rk]=function(b){return a.handleEvent(b)})};(0,_.Ie)(function(a){mk=a(mk)});
_.sk=function(){this.re=new ak(this);this.Hf=this};(0,_.u)(_.sk,_.Ij);_.sk.prototype[Vj]=!0;_.h=_.sk.prototype;_.h.ei=null;_.h.Qg=(0,_.q)(9);_.h.addEventListener=function(a,b,c,d){(0,_.R)(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){(0,_.nk)(this,a,b,c,d)};
_.h.dispatchEvent=function(a){var b,c=this.ei;if(c)for(b=[];c;c=c.ei)b.push(c);var c=this.Hf,d=a.type||a;if((0,_.pa)(a))a=new _.Kj(a,c);else if(a instanceof _.Kj)a.target=a.target||c;else{var e=a;a=new _.Kj(d,c);(0,_.Ce)(a,e)}var e=!0,f;if(b)for(var g=b.length-1;!a.Mg&&0<=g;g--)f=a.currentTarget=b[g],e=tk(f,d,!0,a)&&e;a.Mg||(f=a.currentTarget=c,e=tk(f,d,!0,a)&&e,a.Mg||(e=tk(f,d,!1,a)&&e));if(b)for(g=0;!a.Mg&&g<b.length;g++)f=a.currentTarget=b[g],e=tk(f,d,!1,a)&&e;return e};
_.h.T=function(){_.sk.J.T.call(this);if(this.re){var a=this.re,b=0,c;for(c in a.A){for(var d=a.A[c],e=0;e<d.length;e++)++b,Zj(d[e]);delete a.A[c];a.B--}}this.ei=null};_.h.P=function(a,b,c,d){return this.re.add(String(a),b,!1,c,d)};_.h.Ea=function(a,b,c,d){return this.re.remove(String(a),b,c,d)}; var tk=function(a,b,c,d){b=a.re.A[String(b)];if(!b)return!0;b=(0,_.Id)(b);for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.A&&g.B==c){var k=g.Jg,l=g.If||g.src;g.Rk&&ck(a.re,g);e=!1!==k.call(l,d)&&e}}return e&&!1!=d.Ax};

_.vk=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1};var yk;var wk;wk=!_.O||(0,_.je)(9);_.xk=!_.Yd&&!_.O||_.O&&(0,_.je)(9)||_.Yd&&(0,_.he)("1.9.1");yk=_.O&&!(0,_.he)("9");_.zk=_.O||_.Xd||_.Zd;_.Ak=function(a){a=a.className;return(0,_.pa)(a)&&a.match(/\S+/g)||[]};_.Bk=function(a,b){for(var c=(0,_.Ak)(a),d=(0,_.Cd)(arguments,1),e=c.length+d.length,f=c,g=0;g<d.length;g++)(0,_.pc)(f,d[g])||f.push(d[g]);a.className=c.join(" ");return c.length==e};
var Jk;var Wk;var Vk;var Uk;var Hk;var Fk;_.Dk=function(a,b){var c=b||window.document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):(0,_.Ck)(window.document,"*",a,b)};_.Ek=function(a,b){var c=b||window.document,d=null;c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=(0,_.Ck)(window.document,"*",a,b)[0];return d||null};
_.Ck=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,g;g=a[f];f++)b==g.nodeName&&(d[e++]=g);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;g=a[f];f++)b=g.className,"function"==typeof b.split&&(0,_.pc)(b.split(/\s+/),c)&&(d[e++]=g);d.length=e;return d}return a};
_.Gk=function(a,b){(0,_.ye)(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Fk?a.setAttribute(Fk[d],b):(0,_.Pb)(d,"aria-")||(0,_.Pb)(d,"data-")?a.setAttribute(d,b):a[d]=b})};Fk={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.Ik=function(a,b){var c=b[0],d=b[1];if(!wk&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',(0,_.gc)(d.name),'"');if(d.type){c.push(' type="',(0,_.gc)(d.type),'"');var e={};(0,_.Ce)(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&((0,_.pa)(d)?c.className=d:(0,_.ma)(d)?_.Bk.apply(null,[c].concat(d)):(0,_.Gk)(c,d));2<b.length&&Hk(a,c,b,2);return c};
Hk=function(a,b,c,d){function e(c){c&&b.appendChild((0,_.pa)(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];!(0,_.Vb)(f)||(0,_.Tb)(f)&&0<f.nodeType?e(f):(0,_.kc)(Jk(f)?(0,_.Id)(f):f,e)}};_.Lk=function(a,b){Hk((0,_.Kk)(a),a,arguments,1)};_.Mk=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.Nk=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};_.Ok=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};
_.Pk=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return(0,_.Ok)(a)}};_.Qk=function(a){if(void 0!=a.firstElementChild)a=a.firstElementChild;else for(a=a.firstChild;a&&1!=a.nodeType;)a=a.nextSibling;return a};_.Rk=function(a){return(0,_.Tb)(a)&&1==a.nodeType};
_.Sk=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.Kk=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
_.Tk=function(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else(0,_.Mk)(a),a.appendChild((0,_.Kk)(a).createTextNode(String(b)))};Uk={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1};Vk={IMG:" ",BR:"\n"};
_.Xk=function(a){if(yk&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Wk(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");yk||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a};_.Yk=function(a){var b=[];Wk(a,b,!1);return b.join("")};
Wk=function(a,b,c){if(!(a.nodeName in Uk))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Vk)b.push(Vk[a.nodeName]);else for(a=a.firstChild;a;)Wk(a,b,c),a=a.nextSibling};Jk=function(a){if(a&&"number"==typeof a.length){if((0,_.Tb)(a))return"function"==typeof a.item||"string"==typeof a.item;if((0,_.Sb)(a))return"function"==typeof a.item}return!1};_.Zk=function(a){this.A=a||_.r.document||window.document};_.h=_.Zk.prototype;_.h.I=(0,_.q)(13);
_.h.V=function(a,b,c){return(0,_.Ik)(this.A,arguments)};_.h.createElement=function(a){return this.A.createElement(a)};_.h.Ga=function(){var a=this.A;return a.parentWindow||a.defaultView};_.h.appendChild=function(a,b){a.appendChild(b)};_.h.append=_.Lk;_.h.Nu=_.Mk;_.h.Tv=_.Nk;_.h.removeNode=_.Ok;_.h.FC=_.Pk;_.h.pu=_.Qk;_.h.isElement=_.Rk;_.h.contains=_.Sk;

var ql;var nl;var jl;_.$k=function(a){return"CSS1Compat"==a.compatMode};_.al=function(a){return!_.Zd&&(0,_.$k)(a)?a.documentElement:a.body||a.documentElement};_.bl=function(a,b){this.width=a;this.height=b};_.h=_.bl.prototype;_.h.clone=function(){return new _.bl(this.width,this.height)};_.h.isEmpty=function(){return!(this.width*this.height)};_.h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
_.h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};_.h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.cl=function(a,b){this.x=(0,_.fa)(a)?a:0;this.y=(0,_.fa)(b)?b:0};_.h=_.cl.prototype;_.h.clone=function(){return new _.cl(this.x,this.y)};_.h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};
_.h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};_.h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};_.h.translate=(0,_.q)(12);_.dl=function(a){var b=(0,_.al)(a);a=a.parentWindow||a.defaultView;return _.O&&(0,_.he)("10")&&a.pageYOffset!=b.scrollTop?new _.cl(b.scrollLeft,b.scrollTop):new _.cl(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
_.el=function(a){a=a.document;a=(0,_.$k)(a)?a.documentElement:a.body;return new _.bl(a.clientWidth,a.clientHeight)};_.Zk.prototype.I=(0,_.K)(13,function(a){return(0,_.pa)(a)?this.A.getElementById(a):a});_.fl=function(a){return(0,_.dl)(a.A)};_.gl=function(a){return(0,_.$k)(a.A)};_.hl=function(a){return a?a.parentWindow||a.defaultView:window};_.il=function(a){return(0,_.el)(a||window)};_.kl=function(a){return a?new _.Zk((0,_.Kk)(a)):jl||(jl=new _.Zk)};
_.ll=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};_.ml=function(a){return(0,_.pa)(a)?window.document.getElementById(a):a};nl=function(a){var b=(0,_.pa)(void 0)?(0,_.ll)(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};_.ol=function(a,b){for(var c in b)a[c]=b[c]};_.pl=function(a){a.ka=function(){return a.Uv?a.Uv:a.Uv=new a}}; ql=function(){return _.Zd?"Webkit":_.Yd?"Moz":_.O?"ms":_.Xd?"O":null};_.rl=function(){return _.Zd?"-webkit":_.Yd?"-moz":_.O?"-ms":_.Xd?"-o":null};
var Dl;var Hl;var yl;var sl;_.U=function(a,b,c){(0,_.pa)(b)?sl(a,c,b):(0,_.ye)(b,(0,_.va)(sl,a))};sl=function(a,b,c){(c=(0,_.tl)(a,c))&&(a.style[c]=b)};_.tl=function(a,b){var c=(0,_.fc)(b);if(void 0===a.style[c]){var d=ql()+nl(b);if(void 0!==a.style[d])return d}return c};_.ul=function(a,b){var c=(0,_.Kk)(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""};
_.vl=function(a,b){return a.currentStyle?a.currentStyle[b]:null};_.wl=function(a,b){return(0,_.ul)(a,b)||(0,_.vl)(a,b)||a.style&&a.style[b]};_.xl=function(a){return(0,_.wl)(a,"position")};yl=function(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}_.O&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b};
_.zl=function(a){if(_.O&&!(0,_.je)(8))return a.offsetParent;var b=(0,_.Kk)(a),c=(0,_.wl)(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=(0,_.wl)(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null};
_.Al=function(a){var b,c=(0,_.Kk)(a),d=(0,_.wl)(a,"position"),e=_.Yd&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),f=new _.cl(0,0),g;b=c?(0,_.Kk)(c):window.document;g=!_.O||(0,_.je)(9)||(0,_.gl)((0,_.kl)(b))?b.documentElement:b.body;if(a==g)return f;if(a.getBoundingClientRect)b=yl(a),a=(0,_.fl)((0,_.kl)(c)),f.x=b.left+a.x,f.y=b.top+a.y;else if(c.getBoxObjectFor&&!e)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(g),f.x=b.screenX-a.screenX,
f.y=b.screenY-a.screenY;else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;b!=a&&(f.x+=b.clientLeft||0,f.y+=b.clientTop||0);if(_.Zd&&"fixed"==(0,_.xl)(b)){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(_.Xd||_.Zd&&"absolute"==d)f.y-=c.body.offsetTop;for(b=a;(b=(0,_.zl)(b))&&b!=c.body&&b!=g;)f.x-=b.scrollLeft,_.Xd&&"TR"==b.tagName||(f.y-=b.scrollTop)}return f};
_.Cl=function(a,b){var c=new _.cl(0,0),d=(0,_.hl)((0,_.Kk)(a)),e=a;do{var f=d==b?(0,_.Al)(e):(0,_.Bl)(e);c.x+=f.x;c.y+=f.y}while(d&&d!=b&&(e=d.frameElement)&&(d=d.parent));return c};
_.Bl=function(a){var b;if(a.getBoundingClientRect)b=yl(a),b=new _.cl(b.left,b.top);else{b=(0,_.fl)((0,_.kl)(a));var c=(0,_.Al)(a);b=new _.cl(c.x-b.x,c.y-b.y)}if(_.Yd&&!(0,_.he)(12)){i:{c=(0,_.fc)("transform");if(void 0===a.style[c]&&(c=ql()+nl("transform"),void 0!==a.style[c])){c=(0,_.rl)()+"-transform";break i}c="transform"}a=(a=(0,_.wl)(a,c)||(0,_.wl)(a,"transform"))?(a=a.match(Dl))?new _.cl((0,window.parseFloat)(a[1]),(0,window.parseFloat)(a[2])):new _.cl(0,0):new _.cl(0,0);a=new _.cl(b.x+a.x,
b.y+a.y)}else a=b;return a};_.Gl=function(a,b,c){if(b instanceof _.bl)c=b.height,b=b.width;else if(void 0==c)throw Error("r");a.style.width=(0,_.El)(b,!0);(0,_.Fl)(a,c)};_.El=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};_.Fl=function(a,b){a.style.height=(0,_.El)(b,!0)};
_.Il=function(a){var b=Hl;if("none"!=(0,_.wl)(a,"display"))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a};Hl=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=_.Zd&&!b&&!c;return(0,_.fa)(b)&&!d||!a.getBoundingClientRect?new _.bl(b,c):(a=yl(a),new _.bl(a.right-a.left,a.bottom-a.top))};_.Jl=_.Yd?"MozUserSelect":_.Zd?"WebkitUserSelect":null;Dl=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;

var jy;var by;var ay;var $x;var Zx;_.Yx=function(a){return"rtl"==(0,_.wl)(a,"direction")};Zx={thin:2,medium:4,thick:6};$x=function(a,b){if(/^\d+px?$/.test(b))return(0,window.parseInt)(b,10);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return e};ay=function(a,b){if("none"==(0,_.vl)(a,b+"Style"))return 0;var c=(0,_.vl)(a,b+"Width");return c in Zx?Zx[c]:$x(a,c)};
by=function(a,b){var c=(0,_.vl)(a,b);return c?$x(a,c):0};_.cy=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};_.h=_.cy.prototype;_.h.clone=function(){return new _.cy(this.top,this.right,this.bottom,this.left)};_.h.contains=function(a){return this&&a?"undefined"!=typeof _.cy&&a instanceof _.cy?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
_.h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};_.h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};_.h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
_.h.translate=(0,_.q)(11);_.dy=function(a){if(_.O&&!(0,_.je)(9)){var b=ay(a,"borderLeft"),c=ay(a,"borderRight"),d=ay(a,"borderTop");a=ay(a,"borderBottom");return new _.cy(d,c,a,b)}b=(0,_.ul)(a,"borderLeftWidth");c=(0,_.ul)(a,"borderRightWidth");d=(0,_.ul)(a,"borderTopWidth");a=(0,_.ul)(a,"borderBottomWidth");return new _.cy((0,window.parseFloat)(d),(0,window.parseFloat)(c),(0,window.parseFloat)(a),(0,window.parseFloat)(b))};
_.ey=function(a){if(_.O){var b=by(a,"paddingLeft"),c=by(a,"paddingRight"),d=by(a,"paddingTop");a=by(a,"paddingBottom");return new _.cy(d,c,a,b)}b=(0,_.ul)(a,"paddingLeft");c=(0,_.ul)(a,"paddingRight");d=(0,_.ul)(a,"paddingTop");a=(0,_.ul)(a,"paddingBottom");return new _.cy((0,window.parseFloat)(d),(0,window.parseFloat)(c),(0,window.parseFloat)(a),(0,window.parseFloat)(b))};_.fy=function(a,b){_.O&&(0,_.fa)(a.cssText)?a.cssText=b:a.innerHTML=b};
_.gy=function(a){if(1==a.nodeType)return(0,_.Bl)(a);var b=(0,_.Sb)(a.OC),c=a;a.targetTouches?c=a.targetTouches[0]:b&&a.A.targetTouches&&(c=a.A.targetTouches[0]);return new _.cl(c.clientX,c.clientY)};_.hy=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};_.hy.prototype.clone=function(){return new _.hy(this.left,this.top,this.width,this.height)};_.iy=function(a){return new _.cy(a.top,a.left+a.width,a.top+a.height,a.left)};_.h=_.hy.prototype;
_.h.contains=function(a){return"undefined"!=typeof _.hy&&a instanceof _.hy?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};_.h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
_.h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};_.h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.h.translate=(0,_.q)(10);jy=function(a,b){return new _.cl(a.x-b.x,a.y-b.y)};_.ky=function(a){var b=(0,_.Al)(a);a=(0,_.Il)(a);return new _.hy(b.x,b.y,a.width,a.height)};
_.ly=function(a){for(var b=new _.cy(0,window.Infinity,window.Infinity,0),c=(0,_.kl)(a),d=c.A.body,e=c.A.documentElement,f=(0,_.al)(c.A);a=(0,_.zl)(a);)if(!(_.O&&0==a.clientWidth||_.Zd&&0==a.clientHeight&&a==d)&&a!=d&&a!=e&&"visible"!=(0,_.wl)(a,"overflow")){var g=(0,_.Al)(a),k;k=a;if(_.Yd&&!(0,_.he)("1.9")){var l=(0,window.parseFloat)((0,_.ul)(k,"borderLeftWidth"));if((0,_.Yx)(k))var m=k.offsetWidth-k.clientWidth-l-(0,window.parseFloat)((0,_.ul)(k,"borderRightWidth")),l=l+m;k=new _.cl(l,(0,window.parseFloat)((0,_.ul)(k,
"borderTopWidth")))}else k=new _.cl(k.clientLeft,k.clientTop);g.x+=k.x;g.y+=k.y;b.top=Math.max(b.top,g.y);b.right=Math.min(b.right,g.x+a.clientWidth);b.bottom=Math.min(b.bottom,g.y+a.clientHeight);b.left=Math.max(b.left,g.x)}d=f.scrollLeft;f=f.scrollTop;b.left=Math.max(b.left,d);b.top=Math.max(b.top,f);c=(0,_.il)(c.Ga());b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null};
_.my=function(a,b,c){var d,e=_.Yd&&(_.Pd||_.Td)&&(0,_.he)("1.9");b instanceof _.cl?(d=b.x,b=b.y):(d=b,b=c);a.style.left=(0,_.El)(d,e);a.style.top=(0,_.El)(b,e)};_.ny=function(a,b,c){c||(a=a.parentNode);for(c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null};_.oy=function(a,b,c){return Math.min(Math.max(a,b),c)};
_.qy=function(a,b,c,d,e,f,g,k,l){var m,n;if(m=c.offsetParent){var p="HTML"==m.tagName||"BODY"==m.tagName;p&&"static"==(0,_.xl)(m)||(n=(0,_.Al)(m),p||(p=(p=(0,_.Yx)(m))&&_.Yd?-m.scrollLeft:!p||_.O&&(0,_.he)("8")||"visible"==(0,_.wl)(m,"overflowX")?m.scrollLeft:m.scrollWidth-m.clientWidth-m.scrollLeft,n=jy(n,new _.cl(p,m.scrollTop))))}m=n||new _.cl;n=(0,_.ky)(a);if(p=(0,_.ly)(a)){var t=new _.hy(p.left,p.top,p.right-p.left,p.bottom-p.top),p=Math.max(n.left,t.left),z=Math.min(n.left+n.width,t.left+t.width);
if(p<=z){var w=Math.max(n.top,t.top),t=Math.min(n.top+n.height,t.top+t.height);w<=t&&(n.left=p,n.top=w,n.width=z-p,n.height=t-w)}}p=(0,_.kl)(a);w=(0,_.kl)(c);p.A!=w.A&&(z=p.A.body,w=(0,_.Cl)(z,w.Ga()),w=jy(w,(0,_.Al)(z)),_.O&&!(0,_.gl)(p)&&(w=jy(w,(0,_.fl)(p))),n.left+=w.x,n.top+=w.y);a=(0,_.py)(a,b);b=new _.cl(a&2?n.left+n.width:n.left,a&1?n.top+n.height:n.top);b=jy(b,m);e&&(b.x+=(a&2?-1:1)*e.x,b.y+=(a&1?-1:1)*e.y);var v;if(g)if(l)v=l;else if(v=(0,_.ly)(c))v.top-=m.y,v.right-=m.x,v.bottom-=m.y,v.left-=
m.x;t:{l=b.clone();e=0;a=(0,_.py)(c,d);d=(0,_.Il)(c);k=k?k.clone():d.clone();if(f||0!=a)a&2?l.x-=k.width+(f?f.right:0):f&&(l.x+=f.left),a&1?l.y-=k.height+(f?f.bottom:0):f&&(l.y+=f.top);if(g&&(v?(f=l,e=0,65==(g&65)&&(f.x<v.left||f.x>=v.right)&&(g&=-2),132==(g&132)&&(f.y<v.top||f.y>=v.bottom)&&(g&=-5),f.x<v.left&&g&1&&(f.x=v.left,e|=1),f.x<v.left&&f.x+k.width>v.right&&g&16&&(k.width=Math.max(k.width-(f.x+k.width-v.right),0),e|=4),f.x+k.width>v.right&&g&1&&(f.x=Math.max(v.right-k.width,v.left),e|=1),
g&2&&(e=e|(f.x<v.left?16:0)|(f.x+k.width>v.right?32:0)),f.y<v.top&&g&4&&(f.y=v.top,e|=2),f.y<=v.top&&f.y+k.height<v.bottom&&g&32&&(k.height=Math.max(k.height-(v.top-f.y),0),f.y=v.top,e|=8),f.y>=v.top&&f.y+k.height>v.bottom&&g&32&&(k.height=Math.max(k.height-(f.y+k.height-v.bottom),0),e|=8),f.y+k.height>v.bottom&&g&4&&(f.y=Math.max(v.bottom-k.height,v.top),e|=2),g&8&&(e=e|(f.y<v.top?64:0)|(f.y+k.height>v.bottom?128:0)),g=e):g=256,e=g,e&496)){c=e;break t}(0,_.my)(c,l);d==k||d&&k&&d.width==k.width&&
d.height==k.height||(f=(0,_.gl)((0,_.kl)((0,_.Kk)(c))),!_.O||f&&(0,_.he)("8")?(c=c.style,_.Yd?c.MozBoxSizing="border-box":_.Zd?c.WebkitBoxSizing="border-box":c.boxSizing="border-box",c.width=Math.max(k.width,0)+"px",c.height=Math.max(k.height,0)+"px"):(g=c.style,f?(f=(0,_.ey)(c),c=(0,_.dy)(c),g.pixelWidth=k.width-c.left-f.left-f.right-c.right,g.pixelHeight=k.height-c.top-f.top-f.bottom-c.bottom):(g.pixelWidth=k.width,g.pixelHeight=k.height)));c=e}return c}; _.py=function(a,b){return(b&4&&(0,_.Yx)(a)?b^2:b)&-5};
_.ry=function(){};_.ry.prototype.Sa=function(){};
_.sy=function(a){var b=(0,_.kl)(void 0),c=null,d=b.A;_.O&&d.createStyleSheet?(c=d.createStyleSheet(),(0,_.fy)(c,a)):(d=(0,_.Ck)(b.A,"head",void 0,void 0)[0],d||(c=(0,_.Ck)(b.A,"body",void 0,void 0)[0],d=b.V("head"),c.parentNode.insertBefore(d,c)),c=b.V("style"),(0,_.fy)(c,a),b.appendChild(d,c));return c};_.ty=function(a,b){a.style.display=b?"":"none"};
_.uy=function(a,b){var c=a.style;"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*b+")")};_.vy=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};_.wy=function(a,b){var c={},d;for(d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c};
_.xy=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e;if((0,_.ma)(d)||(e=(0,_.Vb)(d))&&Object.prototype.hasOwnProperty.call(d,"callee"))a.push.apply(a,d);else if(e)for(var f=a.length,g=d.length,k=0;k<g;k++)a[f+k]=d[k];else a.push(d)}};

_.yy=function(){var a=window,b=a.document,c=0;if(b){var a=(0,_.el)(a).height,c=b.body,d=b.documentElement;if((0,_.$k)(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{var b=d.scrollHeight,e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}}return c};_.zy=function(a){this.S=a;this.A=a.Ta()};_.zy.prototype.Ha=function(){Ay(this)};_.zy.prototype.onBeforeParentOpen=_.zy.prototype.Ha;
var Ay=function(a){var b=a.S.Bb();if(a.A.anchorBox&&b&&b.Ca())b=(0,_.Al)(b.Ca()),a.A.anchorBox.left+=b.x,a.A.anchorBox.top+=b.y;else{b=a.A.anchor;if("_default"!=b&&"_iframe"!=b){var c=(0,_.ml)(b);if(c)a.A.anchorBox=(0,_.ky)(c);else{(0,_.Ib)("Anchor not found in DOM: "+b+'. Falling back to "_default".');a.A.anchor="_default";return}}"_iframe"==b&&(b=(0,_.il)(),a.A.anchorBox=new _.hy(0,0,b.width,b.height))}a.A.anchor=""};
_.By=function(a){_.zy.call(this,a)};(0,_.u)(_.By,_.zy);_.By.prototype.open=function(){var a=this.A,b=window.document.createElement("ins");window.document.getElementById(a.container).appendChild(b);b.style.display="block";(0,_.U)(b,a.containerCss);this.S.Kd(b);this.S.sd(b)};_.By.prototype.Vb=function(){window.document.getElementById(this.S.id).style.height=this.S.height+"px"};_.By.prototype.close=function(){(0,_.Ok)(this.S.Ja());(0,_.Ok)(this.Z);this.Z=null};
_.Ey=function(a){if(a.Z)return a.Z;var b=a.A;!b.anchorBox&&b.anchor&&Ay(a);var c=a.S.Bb();if("_default"==b.anchor&&c){var d=(0,_.ky)((0,_.ml)(c.Ja()));b.anchorBox=d}if(!b.anchorBox)return(0,_.Ib)("No anchor box defined."),null;b=new _.cl(b.anchorBox.left,b.anchorBox.top);c&&(c=(0,_.Cl)(c.Ca(),window),a.W=new _.cl,a.W.x=c.x,a.W.y=c.y,b.x+=c.x,b.y+=c.y,(0,_.Cy)(b));a.ia=b;c=(0,_.Dy)(a,!0);a.Z=window.document.createElement("ins");a.Z.style.cssText=c;window.document.body.appendChild(a.Z);return a.Z};
_.Dy=function(a,b){var c=a.A;return"position: absolute !important;background-color: transparent !important;left: "+a.ia.x+"px !important;top: "+a.ia.y+"px !important;width: "+c.anchorBox.width+"px !important;height: "+c.anchorBox.height+"px !important;z-index: -10000 !important;display: "+(b?"block":"none")+" !important;"};
_.Fy=function(a,b){var c=0,d=0;if(b.pageX||b.pageY)c=b.pageX,d=b.pageY;else if(b.clientX||b.clientY){var c=b.target?b.target:b.srcElement,e;c.ownerDocument&&c.ownerDocument.parentWindow?e=c.ownerDocument.parentWindow:e=window;d=c=0;_.O?(c=e.document.documentElement.scrollLeft,d=e.document.documentElement.scrollTop):(c=e.pageXOffset,d=e.pageYOffset);c=b.clientX+c;d=b.clientY+d}e=new _.cl(c,d);return(c=(0,_.iy)((0,_.ky)(a)))&&c.contains(e)};
_.Cy=function(a){var b=window,c=window.document.body,d=(0,_.Al)(c),b=c.currentStyle||b.getComputedStyle(c,"");b.position&&"static"!=b.position&&(a.x-=d.x,a.y-=d.y)};_.Gy=function(a){var b=a.S.Bb()&&a.S.Bb().Ja(),b=b&&b.style.zIndex?(0,window.parseInt)(b.style.zIndex,10)+1:0;return Math.min(2147483647,Math.max(2E9,a.A.zIndex||b))};
var Jy;var Iy;var Hy;Hy={"bottom-center":1,"bottom-end":7,"bottom-left":1,"bottom-right":3,"bottom-start":5,"left-bottom":1,"left-center":0,"left-top":0,"right-bottom":3,"right-center":2,"right-top":2,"top-center":0,"top-end":6,"top-left":0,"top-right":2,"top-start":4};Iy={"bottom-center":!0,"top-center":!0};Jy={"left-center":!0,"right-center":!0};
_.Ky=function(a,b,c,d,e){e=e||{x:0,y:0};if(Iy[b]){var f=(0,_.Il)(a).width/2;e.x="top-right"==d||"bottom-right"==d?e.x+f:e.x-f}Iy[d]&&(f=(0,_.Il)(c).width/2,e.x+=f);Jy[b]&&(f=(0,_.Il)(a).height/2,e.y="right-bottom"==d||"left-bottom"==d?e.y+f:e.y-f);Jy[d]&&(e.y+=(0,_.Il)(c).height/2);(0,_.qy)(c,Hy[d],a,Hy[b],new _.cl(e.x,e.y));d=(0,_.ny)(a,function(a){if(a==window.document)return!1;a=(0,_.xl)(a);return!!a&&"static"!=a});c=b=0;d&&(c=(0,_.Al)(d),b=-c.x,c=-c.y);a=a.style;(0,window.parseInt)(a.left,10)< b&&(a.left=b+"px");(0,window.parseInt)(a.top,10)<c&&(a.top=c+"px")};
_.Ly=function(a){_.zy.call(this,a.S);this.F=a;this.B=null};(0,_.u)(_.Ly,_.By);_.Ly.prototype.Ha=function(){this.F.Ha()};_.Ly.prototype.onBeforeParentOpen=_.Ly.prototype.Ha;_.Ly.prototype.open=function(){this.F.open();if(this.A.closeClickDetection||this.A.hideClickDetection)this.B=(0,_.R)(window.document,["click","touchstart"],(0,_.s)(this.C,this),!1)};_.Ly.prototype.open=_.Ly.prototype.open;_.Ly.prototype.Vb=function(a){this.F.Vb(a)};_.Ly.prototype.onready=_.Ly.prototype.Vb;
_.Ly.prototype.D=function(a){this.F.onRenderStart&&this.F.onRenderStart(a)};_.Ly.prototype.onRenderStart=_.Ly.prototype.D;_.Ly.prototype.close=function(){if(this.A.closeClickDetection||this.A.hideClickDetection)(0,_.ok)(this.B),this.B=null;this.F.close()};_.Ly.prototype.close=_.Ly.prototype.close;_.Ly.prototype.C=function(a){(0,_.Fy)(this.S.Ja(),a)||(this.A.hideClickDetection&&this.F.show?this.F.show(!1):this.F.close())};

_.LE=function(a){_.zy.call(this,a.S);this.F=a;this.B=null};(0,_.u)(_.LE,_.By);_.LE.prototype.open=function(){this.A.targetPos=this.A.targetPos||"top-start";this.A.anchorPos=this.A.anchorPos||"bottom-start";var a=(0,_.Ey)(this),b=this.S.Ja();b?(b.style.visibility="hidden",b.style.position="absolute",a.parentNode.appendChild(b)):this.F.open()};_.LE.prototype.open=_.LE.prototype.open;
_.LE.prototype.Vb=function(){if(this.A.closeClickDetection){var a=this,b=function(b){(0,_.Fy)(a.S.Ja(),b)||(a.S.close(),a.B=null)};window.document.A?(window.document.A("click",b),this.B=function(){window.document.removeEventListener("click",b,!1)}):window.document.attachEvent&&(window.document.attachEvent("onclick",b),this.B=function(){window.document.detachEvent("onclick",b)})}var c=this.S.Ja();window.document.getElementById(this.S.id).style.height=this.S.height+"px";var d=(0,_.Ey)(this);d&&(0,_.Ky)(c,
this.A.targetPos,d,this.A.anchorPos,{x:this.A.leftOffset||0,y:this.A.topOffset||0});c.style.visibility="visible"};_.LE.prototype.onready=_.LE.prototype.Vb;_.LE.prototype.close=function(){this.F.close();this.B&&this.B()};_.LE.prototype.close=_.LE.prototype.close;
var NE;_.ME=function(a){_.zy.call(this,a)};(0,_.u)(_.ME,_.By);NE=["transition","WebkitTransition","MozTransition","OTranstion","msTransition"];_.OE=function(a,b){a.B=window.document.createElement("div");var c={position:"absolute",top:"-10000px",zIndex:(0,_.Gy)(a)};a.A.width&&(c.width=a.A.width+"px");for(var d in c)a.B.style[d]=c[d];(b||window.document.body).appendChild(a.B)};_.ME.prototype.open=function(a){this.S.Ec("updateContainer",(0,_.s)(this.C,this));(0,_.OE)(this,a);this.S.sd(this.B);this.S.Kd(this.B)};
_.ME.prototype.open=_.ME.prototype.open;_.ME.prototype.Vb=function(){var a=PE(this);if(a){var b=window.document.getElementById(this.S.da());b.style.height=a.height+"px";b.style.width=a.width+"px";this.S.width=a.width;this.S.height=a.height;b.style.boxShadow="0 4px 16px rgba(0, 0, 0, 0.3)"}};_.ME.prototype.onready=_.ME.prototype.Vb;_.ME.prototype.close=function(){this.B.parentNode&&this.B.parentNode.removeChild(this.B)};_.ME.prototype.close=_.ME.prototype.close;
_.ME.prototype.C=function(a,b,c){var d=this.S.Ja();d&&(a?(QE(this,b,c),d.style.opacity=0,d.style.display="",window.setTimeout((0,_.s)(function(){RE(d,!0);d.style.opacity=1},this),0)):(d.style.display="none",RE(d,!1),d.style.opacity=0))};
var RE=function(a,b){for(var c=0;c<NE.length;c++)a.style[NE[c]]=b?"opacity .13s linear":""},QE=function(a,b,c){var d=a.S.Bb();b+=10;c+=10;if(_.J.pa&&(d&&(d=(0,_.Cl)(d.Ja(),window),b+=d.x,c+=d.y),d=PE(a))){var e=(0,_.il)(window),f=(0,_.dl)(window.document);e.width&&(b=Math.min(b,e.width+f.x-d.width-8),c+d.height>e.height+f.y-8&&(c-=20+d.height,c=Math.max(c,Math.min(f.y+1,(0,_.yy)()-d.height))))}a=a.S.Ja();a.style.left=b+"px";a.style.top=c+"px"},PE=function(a){return a.S.width&&a.S.height?{width:a.S.width, height:a.S.height}:(a=a.S.Ca())&&a.offsetWidth&&a.offsetHeight?{width:a.offsetWidth,height:a.offsetHeight}:null};
_.SE=function(a){_.zy.call(this,a)};(0,_.u)(_.SE,_.By);_.SE.prototype.C=null;_.SE.prototype.D=null;_.SE.prototype.B=null;var TE={end:"start",left:"right",right:"left",start:"end"},UE={top:"bottom",bottom:"top"};_.SE.prototype.open=function(){var a=window.document.createElement("div");(0,_.U)(a,{top:"-10000px",position:"absolute",zIndex:(0,_.Gy)(this)});(0,_.Ey)(this).parentNode.appendChild(a);this.S.Kd(a);this.S.sd(a)};_.SE.prototype.open=_.SE.prototype.open;
_.SE.prototype.Vb=function(){var a=window.document.getElementById(this.S.id);a.style.height=this.S.height+"px";a.style.width=this.S.width+"px";a.style.boxShadow="0 4px 16px rgba(0, 0, 0, 0.3)";var b=this.S.Ja();b.style.lineHeight=0;var c=(0,_.Ey)(this),d=this.A.targetPos||"top-start",e=this.A.anchorPos||"bottom-start",f=this.A.leftOffset||0,g=this.A.topOffset||0;(0,_.Ky)(b,d,c,e,{x:f,y:g});var k=(0,_.il)(window),l=(0,_.dl)(window.document),m=b.offsetLeft<l.x||b.offsetLeft+b.offsetWidth>k.width+l.x,
k=b.offsetTop<l.y||b.offsetTop+b.offsetHeight>k.height+l.y,d=VE(d,m,k),e=VE(e,m,k);(0,_.Ky)(b,d,c,e,{x:f*(m?-1:1),y:g*(k?-1:1)});b.style.visibility="visible";this.C=(0,_.R)(window.document,"mouseover",(0,_.s)(function(b){b.target===a&&this.B&&(window.clearTimeout(this.B),this.B=null)},this));this.D=(0,_.R)(window.document,"mouseout",(0,_.s)(function(b){b.target===a&&(this.B=window.setTimeout((0,_.s)(this.S.close,this.S),1E3))},this))};_.SE.prototype.onready=_.SE.prototype.Vb;
var VE=function(a,b,c){a=a.split("-");for(var d=0;2>d;d++)b&&TE[a[d]]&&(a[d]=TE[a[d]]),c&&UE[a[d]]&&(a[d]=UE[a[d]]);return a.join("-")};_.SE.prototype.close=function(){this.C&&((0,_.ok)(this.C),(0,_.ok)(this.D),this.D=this.C=null);this.B&&(window.clearTimeout(this.B),this.B=null);_.SE.J.close.call(this)};_.SE.prototype.close=_.SE.prototype.close;

var HM;var GM;var FM;for(_.EM=function(a){return{Ta:function(){return a},Bb:function(){return a.openerIframe}}},FM=function(a){(new _.zy((0,_.EM)(a))).Ha()},GM="bubble circlepicker float hover hover-menu slide-menu".split(" "),HM=0;HM<GM.length;HM++)_.Mi[GM[HM]]=FM;

_.Pi.hover=function(a){var b=new _.ME((0,_.EM)(a));(0,_.OE)(b,a.where);a.where=b.B;a.onClose=function(){b.close()};a.onRestyle=function(a){if(a.updateContainer){var d=a.updateContainer;b.C(d.visible,d.x,d.y)}a.width&&(b.S.width=a.width);a.height&&(b.S.height=a.height)};a.onCreate=function(c){b.S=c;c.Bb=function(){return a.openerIframe};c.register("_ready",(0,_.s)(b.Vb,b),_.Ai);c.updateContainer=function(a,c,f){b.C(a,c,f)}}};

var bJ=function(a,b){this.A=a;this.th=b};_.cJ=function(a){this.w=this.Ye=a;this.n=null;this.slf=0;this.ssh=!1;this.sen=!0;this.shl=this.itm=null};_.cJ.prototype.sm=function(a,b){this.Ye.qi(new bJ(a,this));this.n=b};_.cJ.prototype.sh=function(){this.Ye.show()};_.cJ.prototype.hi=function(){this.Ye.jb()};_.cJ.prototype.cl=function(){this.Ye.close()};_.cJ.prototype.en=function(){this.Ye.enable()};_.cJ.prototype.di=function(){this.Ye.disable()};_.cJ.prototype.hl=function(a){this.Ye.eD(a)};_.cJ.prototype.vr=function(a,b){this.Ye.FD(a,b)};

_.pi.F("ytsubscribe",function(a,b){var c=_.pi.B;c&&_.pi.M({role:"ytsubscribe",iframe:c,data:b},{role:"ytrelay",iframe:a})},void 0,_.Ai);
_.Cq=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};_.Dq=function(a,b,c){return(0,_.Ik)(window.document,arguments)};_.Eq="StopIteration"in _.r?_.r.StopIteration:Error("v");_.Fq=function(){};_.Fq.prototype.next=function(){throw _.Eq;};_.Fq.prototype.Ve=function(){return this};
_.Gq=function(a,b){this.B={};this.A=[];this.D=this.C=0;var c=arguments.length;if(1<c){if(c%2)throw Error("j");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.Gq?(c=a.Wc(),d=a.Gb()):(c=(0,_.Ae)(a),d=(0,_.ze)(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.h=_.Gq.prototype;_.h.Ya=function(){return this.C};_.h.Gb=function(){Iq(this);for(var a=[],b=0;b<this.A.length;b++)a.push(this.B[this.A[b]]);return a};_.h.Wc=function(){Iq(this);return this.A.concat()};
_.h.nh=(0,_.q)(14);_.h.equals=function(a,b){if(this===a)return!0;if(this.C!=a.Ya())return!1;var c=b||Jq;Iq(this);for(var d,e=0;d=this.A[e];e++)if(!c(this.get(d),a.get(d)))return!1;return!0};var Jq=function(a,b){return a===b};_.Gq.prototype.isEmpty=function(){return 0==this.C};_.Gq.prototype.clear=function(){this.B={};this.D=this.C=this.A.length=0};_.Gq.prototype.remove=function(a){return(0,_.Kq)(this.B,a)?(delete this.B[a],this.C--,this.D++,this.A.length>2*this.C&&Iq(this),!0):!1};
var Iq=function(a){if(a.C!=a.A.length){for(var b=0,c=0;b<a.A.length;){var d=a.A[b];(0,_.Kq)(a.B,d)&&(a.A[c++]=d);b++}a.A.length=c}if(a.C!=a.A.length){for(var e={},c=b=0;b<a.A.length;)d=a.A[b],(0,_.Kq)(e,d)||(a.A[c++]=d,e[d]=1),b++;a.A.length=c}};_.h=_.Gq.prototype;_.h.get=function(a,b){return(0,_.Kq)(this.B,a)?this.B[a]:b};_.h.set=function(a,b){(0,_.Kq)(this.B,a)||(this.C++,this.A.push(a),this.D++);this.B[a]=b};
_.h.forEach=function(a,b){for(var c=this.Wc(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.h.clone=function(){return new _.Gq(this)};_.h.Ve=function(a){Iq(this);var b=0,c=this.A,d=this.B,e=this.D,f=this,g=new _.Fq;g.next=function(){for(;;){if(e!=f.D)throw Error("x");if(b>=c.length)throw _.Eq;var g=c[b++];return a?g:d[g]}};return g};_.Kq=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};

var TM=function(a){a.A.os(a.th)},UM=function(a){this.th=a;this.Lc=0;this.kk=!1;this.Tt=!0;this.Wf=null};UM.prototype.zf=function(){return this.th};var VM=function(a){return 5==a.Lc||4==a.Lc};UM.prototype.isEnabled=function(){return this.Tt};UM.prototype.Ka=function(a){this.Tt=a};
var WM=function(a,b,c){this.A=a||{};this.B=b||0;this.D=c||0;a={};b=(0,_.s)(this.ju,this);a.fc=b;b=(0,_.s)(this.Dq,this);a.rc=b;b=(0,_.s)(this.kr,this);a.sc=b;b=(0,_.s)(this.Kj,this);a.hc=b;b=(0,_.s)(this.Zi,this);a.cc=b;b=(0,_.s)(this.qv,this);a.os=b;b=(0,_.s)(this.pv,this);a.or=b;b=(0,_.s)(this.nv,this);a.oh=b;b=(0,_.s)(this.lv,this);a.oc=b;b=(0,_.s)(this.mv,this);a.oe=b;b=(0,_.s)(this.ov,this);a.oi=b;this.C=a};_.h=WM.prototype;
_.h.Dq=function(a,b,c){try{a=a+(null!=b?"_"+b:""),c.sm(this.C,a),this.A[a]=new UM(c)}catch(d){return!1}return!0};_.h.ju=function(a,b){var c=this.A[a+(null!=b?"_"+b:"")];return c?c.zf():null};_.h.kr=function(a){var b=XM(this,a);if(b&&(2==b.Lc||3==b.Lc)&&b.isEnabled()&&!b.kk){try{a.sh()}catch(c){}b.kk=!0}};_.h.Kj=function(a){var b=XM(this,a);if(b&&(2==b.Lc||3==b.Lc||VM(b))&&b.kk){try{a.hi()}catch(c){}b.kk=!1}};
_.h.Zi=function(a){var b=XM(this,a);if(b&&5!=b.Lc){try{this.Kj(a),a.cl()}catch(c){}YM(this,b)}};_.h.qv=function(a){(a=XM(this,a))&&0==a.Lc&&(ZM(this,a),a.Lc=1)};var ZM=function(a,b){if(a.B){var c=(0,window.setTimeout)((0,_.s)(function(){VM(b)||$M(this,b)},a),a.B);b.Wf=c}else $M(a,b)},$M=function(a,b){var c=a.D-a.B;0<c&&(c=(0,window.setTimeout)((0,_.s)(function(){VM(b)||(b.Lc=4,this.Zi(b.zf()))},a),c),b.Wf=c)},aN=function(a){null!=a.Wf&&((0,window.clearTimeout)(a.Wf),a.Wf=null)};_.h=WM.prototype;
_.h.pv=function(a){(a=XM(this,a))&&!VM(a)&&1==a.Lc&&(aN(a),a.Lc=3)};_.h.nv=function(a){(a=XM(this,a))&&!VM(a)&&(a.kk=!1)};_.h.lv=function(a){var b=XM(this,a);if(b&&!VM(b)){try{this.Kj(a)}catch(c){}YM(this,b)}};_.h.mv=function(a){(a=XM(this,a))&&!VM(a)&&(a.Lc=4,this.Zi(a.zf()))};_.h.ov=function(a,b){var c=XM(this,a);c&&!VM(c)&&2<=b&&4>=b&&!VM(c)&&(aN(c),c.Lc=2)};var YM=function(a,b){aN(b);b.Lc=5;var c=a.A,d;for(d in c)c[d]==b&&delete c[d]},XM=function(a,b){return a.A[b.n]},bN=function(){WM.call(this)};
(0,_.u)(bN,WM);var cN=function(a){this.A=a};_.h=cN.prototype;_.h.Dq=function(a,b,c){return this.A.rc(a,b,c)};_.h.ju=function(a,b){return this.A.fc(a,b)};_.h.kr=function(a){this.A.sc(a)};_.h.Kj=function(a){this.A.hc(a)};_.h.Zi=function(a){this.A.cc(a)};_.h.qv=function(a){this.A.os(a)};_.h.pv=function(a,b){this.A.or(a,b)};_.h.nv=function(a){this.A.oh(a)};_.h.lv=function(a){this.A.oc(a)};_.h.mv=function(a,b,c,d,e,f){this.A.oe(a,b,c,d,e,f)};_.h.ov=function(a,b,c,d){this.A.oi(a,b,c,d)};
var dN=function(){return window.___jsl.man},eN=function(a){if(window.___jsl.man)a(window.___jsl.man);else{var b=function(){var b=new bN;window.___jsl.man=b;a(b)};if(window.gbar){var c=function(){if(window.gbar.wg){var c=new cN(window.gbar.wg);window.___jsl.man=c;a(c)}else b()};window.gbar.wg?c():window.gbar.qm(c)}else b()}};
var fN=(0,_.De)("contactid","cmp","email","hl","n","m","p","src","userid","sp","ytid");(0,_.De)("hl","origin","ri","src","userid");var gN=(0,_.De)("nm","s","pr","v");(0,_.Ce)(gN,fN);var hN=/(?:^|\s)g-(?:hovercard|profile)(?:$|\s)/,iN={loadHovercardDelay:250,loadDelay:150,hoverDelay:500,closeDelay:500},jN=0,kN=function(a){return window.document.body==a?"body":a.__cardid||null},lN=function(a){var b=kN(a);b||(b=a.__cardid=jN++);return b},mN=function(a){var b=a.className||"getAttribute"in a&&a.getAttribute("class");return b&&hN.test(b)||"getAttribute"in a&&a.getAttribute("oid")&&36==(0,_.G)("card/p")?!0:"G:HOVERCARD"==a.tagName.toUpperCase()},nN=function(a,b){var c={};(0,_.Ce)(c,
iN,(0,_.G)("iframes/card")||{},(0,_.G)("card")||{});for(var d=[],e=a;e;e=e.parentNode){var f=kN(e);f&&b[f]&&d.push(b[f])}(0,_.kc)(d.reverse(),function(a){(0,_.Ce)(c,a)});d="G:HOVERCARD"==a.tagName.toUpperCase()?"":"data-";e=a.attributes;for(f=0;f<e.length;f++)(0,_.Pb)(e[f].name,d)&&(c[e[f].name.substring(d.length)]=e[f].value);"getAttribute"in a&&a.getAttribute("oid")&&36==(0,_.G)("card/p")&&(c.ytid=a.getAttribute("oid"));!c.userid&&"A"==a.tagName.toUpperCase()&&a.pathname&&(d=a.pathname.match(/^\/?(\d+)$/), /\.google\.com$/.test(a.hostname)&&d&&(c.userid=d[1]));c.hl||(c.hl=(0,_.G)("lang")||_.M.nb().hl||void 0);c.m=c.entity;c.src=c.source;delete c.entity;delete c.source;return c},oN=function(a,b){var c=b[a];(0,_.Ub)(c)||(c=iN[a]);return 0>c?0:c};
var pN=function(a){this.B=a;this.th=new _.cJ(this);this.C=!1;this.D=0};_.h=pN.prototype;_.h.zf=function(){return this.th};
_.h.load=function(a){TM(this.lb);a=(0,_.wy)(a,function(a,b){return fN[b]&&null!=a});a.origin=window.location.protocol+"//"+window.location.host;var b=this,c=this.B,d={_event:function(a){if(!(a.timestamp<c.la)){"sgcp_ams"==a.event?(c.N=!0,c.W=!1):c.N&&"mouseover"==a.event?c.W=!0:c.N&&"mouseout"==a.event?c.W=!1:"sgcp_amh"==a.event&&(c.N=!1,c.W||qN(c));if("mouseover"==a.event||"sgcp_ams"==a.event)window.clearTimeout(c.F),c.F=null;if(a.cpid){for(var b=window.document.getElementById(a.cpid);b&&"BODY"!=
b.parentNode.tagName;)b=b.parentNode;c.ta=b}a.fromCard&&"mouseout"==a.event&&qN(c)}},_ready:(0,_.s)(this.KC,this),version:function(a){rN(c,c.G,{type:"circles_changed",version:a.v})},loaded:function(a){a.ri==b.D&&b.F()},rendered:function(){var a=b.B.M,c=(0,_.fl)((0,_.kl)((window||_.r||window).document));sN(b,!0,a.x+c.x,a.y+c.y);a=b.B;rN(a,a.G,{type:"show",frame:b.A})},renderfailed:function(){sN(b,!1,0,0)},disposed:function(){b.A.close()},cardAction:function(a){tN(c,a)}},e=":card";!(0,_.G)("iframes/card/url")&&
(0,_.G)("iframes/hovercard/url")&&(e=":hovercard");a=(0,_.fi)((0,_.gi)((0,_.hi)((0,_.Zi)((0,_.$i)(new _.ei({disableMultiLevelParentRelay:!0,hover:!0}),d),_.Ai),a),"hover"),e);(0,_.G)("card/relayOpenTop")&&((0,_.ii)(a,-1),(0,_.cj)(new _.di(a.A),"_default"));_.pi.open(a.value(),(0,_.s)(function(a){this.A=a},this))};_.h.KC=function(){this.C=!0;var a=this.lb;a.A.or(a.th,{});a=this.B;a.A&&a.bq(a.A)};_.h.qi=function(a){this.lb=a};_.h.eD=function(a){this.A.send("getHealthc",void 0,a,_.Ai)};
_.h.FD=function(a,b){this.A.send("getVarc",a,b,_.Ai)};var sN=function(a,b,c,d){a.A.updateContainer?a.A.updateContainer(b,c,d):a.A.$j({updateContainer:{visible:b,x:c,y:d}})};_.h=pN.prototype;_.h.show=function(){sN(this,!0,0,-1E4);this.A.send("render",void 0,void 0,_.Ai)};_.h.jb=function(){this.A.send("hide",void 0,void 0,_.Ai);sN(this,!1,0,0);var a=this.B;rN(a,a.G,{type:"hide"});a.G=null;a.Ma=null};_.h.close=function(){this.A.send("dispose",void 0,void 0,_.Ai)};_.h.enable=function(){}; _.h.disable=function(){};
var uN=function(){this.Wa=0;this.ia=[];this.Z={};this.ea={};this.R={};this.la=this.F=this.B=this.K=this.Ma=this.G=this.D=this.A=this.C=null;this.M={x:0,y:0};this.W=this.N=!1;this.ta=null;this.Y=new _.Gq;(0,_.Ej)("gapi.load")("gapi.iframes.style.slide-menu")},vN=0,wN=function(a,b,c,d){var e=lN(b),e=a.R[e]||(a.R[e]={});e[c]||(e[c]=d=(0,_.s)(d,a),b.addEventListener?b.addEventListener(c,d,"focus"==c||"blur"==c):("focus"==c?c="focusin":"blur"==c&&(c="focusout"),b.attachEvent("on"+c,d)))},xN=function(a,
b,c){(a=a.R[lN(b)])&&a[c]&&(b.addEventListener?b.removeEventListener(c,a[c],"focus"==c||"blur"==c):b.detachEvent("focus"==c?"onfocusin":"blur"==c?"onfocusout":"on"+c,a[c]),delete a[c])},yN=function(a,b){var c=a.R[b.id];if(c)for(var d in c)c.hasOwnProperty(d)&&xN(a,b,d)};
uN.prototype.watch=function(a,b,c){if(a=a||window.document.body){this.Wa++;var d=lN(a);b&&(this.Z[d]=b);c&&(this.ea[d]=c);wN(this,a,"mouseover",this.du);wN(this,a,"mouseout",this.Kp);wN(this,a,"mousedown",this.cu);wN(this,a,"focus",this.du);wN(this,a,"blur",this.Kp);wN(this,window.document.body,"mouseout",this.Kp);wN(this,window.document.body,"mousedown",this.cu)}else window.setTimeout((0,_.s)(this.watch,this),100)};
uN.prototype.unwatch=function(a){if(a=a||window.document.body)if(qN(this,0),a!=window.document.body?yN(this,a):xN(this,window.document.body,"mouseover"),a=lN(a),delete this.Z[a],delete this.ea[a],!(0<--this.Wa)){yN(this,window.document.body);var b=this.C;this.Va();this.C=null;window.setTimeout(function(){var a=dN();a&&a.Zi(b.zf())},100)}};uN.prototype.Pb=function(a){this.ia.push(a)};uN.prototype.Og=function(a){(0,_.Gj)(this.ia,a)};
var rN=function(a,b,c){for(var d=[];b;){var e=kN(b);e&&a.Z[e]&&d.push(a.Z[e]);b=b.parentNode}(0,_.xy)(d,a.ia);(0,_.kc)(d,function(a){a(c)})};_.h=uN.prototype;
_.h.du=function(a){this.la=(0,_.za)();var b=a.target||a.srcElement;if(b&&"IFRAME"!=b.tagName){for(;b&&!mN(b);)if(b=b.parentNode,1!=b.nodeType)return;if(b)if(this.G==b||this.A==b)this.F&&(window.clearTimeout(this.F),this.F=null);else{this.A=b;wN(this,b,"mousemove",this.pE);"focus"==a.type||"focusin"==a.type?(a=(0,_.gy)(b),this.M.x=a.x,this.M.y=a.y+b.offsetHeight):(this.M.x=a.clientX,this.M.y=a.clientY);this.K=(0,_.za)();a=this.D=nN(b,this.ea);var c=oN("hoverDelay",a);this.C?this.C.C&&(window.clearTimeout(this.B),
this.B=window.setTimeout((0,_.s)(this.bq,this,b),c-oN("loadDelay",a))):(window.clearTimeout(this.B),this.B=window.setTimeout((0,_.s)(this.EF,this),c-oN("loadHovercardDelay",a)))}}};_.h.Kp=function(a){this.la=(0,_.za)();if("blur"!=a.type||a.target==this.G||a.target==this.A){if(a=a.relatedTarget||a.toElement){if("IFRAME"==a.tagName)return;if(this.ta)for(;a&&"BODY"!=a.tagName;){if(a==this.ta)return;a=a.parentNode}}qN(this)}};_.h.cu=function(){qN(this,0)};
_.h.pE=function(a){this.M.x=a.clientX;this.M.y=a.clientY};_.h.EF=function(){this.B&&(window.clearTimeout(this.B),this.B=null);if(this.A&&(rN(this,this.A,{type:"hover",config:this.D}),!this.C)){var a=this.C=new pN(this);eN((0,_.s)(function(b){b.Dq("card",vN++,a.zf())&&a.load(this.D)},this))}};
_.h.bq=function(a){this.B&&(window.clearTimeout(this.B),this.B=null);if(this.A==a){var b=oN("hoverDelay",this.D)-oN("loadDelay",this.D)-(0,_.za)()+this.K;if(0<b)this.B=window.setTimeout((0,_.s)(this.bq,this,a),b);else{rN(this,a,{type:"hover",config:this.D});var b=this.C,c=this.D;a=(0,_.s)(this.By,this,a);b.C&&(b.F=a,c.ri=++b.D,b.A.send("loadData",c,void 0,_.Ai))}}};
_.h.By=function(a){if(this.A===a&&this.C&&this.C.C&&this.K){var b=oN("hoverDelay",this.D)-(0,_.za)()+this.K;0<b?window.setTimeout((0,_.s)(this.By,this,a),b):(this.Va(),this.G=this.A,this.Ma=this.D,xN(this,this.A,"mousemove"),this.K=this.D=this.A=null,dN().kr(this.C.zf()))}};var qN=function(a,b){a.A&&xN(a,a.A,"mousemove");a.A=null;a.D=null;a.K=null;a.B&&(window.clearTimeout(a.B),a.B=null);!a.F&&a.G&&(a.F=window.setTimeout((0,_.s)(a.Va,a),(0,_.Ub)(b)?b:oN("closeDelay",a.Ma)))};
uN.prototype.Va=function(){this.F&&(window.clearTimeout(this.F),this.F=null);this.G&&dN().Kj(this.C.zf())};var tN=function(a,b){rN(a,null,b);a.Ba&&a.Ba.send("cardAction",b,void 0,a.Ha)};uN.prototype.fo=function(a,b,c){var d={};d.frame=a;d.filter=b||_.zi;d.Cc=c||_.Kd;this.Y.set((0,_.hc)(a),d);a.register("cardAction",(0,_.s)(function(a){tN(this,a);d.Cc(a)},this),d.filter)};
uN.prototype.ho=function(a){this.Ha=a||_.zi;_.pi.D((0,_.s)(function(a){this.Ba=a;this.Ba.register("cardAction",(0,_.s)(this.Pk,this),this.Ha)},this),void 0,this.Ha)};uN.prototype.Pk=function(a){this.Y.isEmpty()||(0,_.kc)(this.Y.Gb(),function(b){b.frame.send("cardAction",a,void 0,b.filter)});this.C&&this.C.A.send("cardAction",a,void 0,_.Ai)};
_.zN=function(){var a={},b=new uN;a.watch=function(a,d,e){b.watch(a,d,e)};a.unwatch=function(a){b.unwatch(a)};a.Pb=function(a){b.Pb(a)};a.Og=function(a){b.Og(a)};a.fo=function(a,d,e){b.fo(a,d,e)};a.ho=function(a){b.ho(a)};a.Pk=function(a){b.Pk(a)};a.X=function(a,b){b.origin=window.location.protocol+"//"+window.location.host;var e=_.pi.Mf({url:":card",where:window.document.getElementById(a),queryParams:b,messageHandlers:{_ready:function(){e.send("loadData",b,void 0,_.Ai)},loaded:function(){e.send("render", void 0,void 0,_.Ai)}},messageHandlersFilter:_.Ai})};return a}();
(0,_.D)("gapi.card.watch",_.zN.watch);(0,_.D)("gapi.card.unwatch",_.zN.unwatch);(0,_.D)("gapi.card.addCallback",_.zN.Pb);(0,_.D)("gapi.card.removeCallback",_.zN.Og);(0,_.D)("gapi.card.render",_.zN.X);(0,_.D)("gapi.card.connectChild",_.zN.fo);(0,_.D)("gapi.card.connectOpener",_.zN.ho);(0,_.D)("gapi.card.broadcast",_.zN.Pk);

});
// Google Inc.
